version: '1'
services:
  composer:
    image: composer:2.7
    volumes:
      - .:/app
    restart: "no"
  php:
    image: php:8.2-cli
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app
  phpunit:
    image: php:8.2-cli
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit